#!/bin/sh
set -e

echo "Generating runtime /usr/share/nginx/html/config.js from container environment..."

cat <<EOF > /usr/share/nginx/html/config.js
/**
 * BrainzOS — Institutional Production Configuration
 * Automatically generated by docker/entrypoint.sh at container boot.
 *
 * NOTE ON SECURITY:
 * The anonKey is a public client token intended to be delivered to browsers.
 * Database security is enforced strictly by PostgreSQL Row Level Security (RLS)
 * via the authenticated JWT (auth.uid()). The service_role key is NEVER exposed here.
 */
window.BRAINZOS_CONFIG = {
  SUPABASE_URL: window.location.origin,
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY:-}"
};
EOF

echo "Runtime config.js generated. Starting Nginx..."
exec nginx -g "daemon off;"
